networks:
  net: ~
services: 
  jenkins: 
    container_name: jenkins
    image: jenkins-ansible
    networks: 
      - net
    ports: 
      - "8080:8080"
    volumes: 
      - "$PWD/jenkins_home:/var/jenkins_home"
    build:
      context: jenkins-ansible 
        
  remote_host:
    container_name: remote_host
    image: remote-host 
    build:
      context: centos7
    networks:
      - net
    volumes:
      - "$PWD/aws-s3-script.sh:/tmp/script.sh"
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks: 
       - net
  web: 
    container_name: web
    image: ansible-web
    build: 
      context: jenkins-ansible/web
    networks: 
      - net
    ports: 
      - "80:80"
  git:
    container_name: git-server
    image: gitlab/gitlab-ce
    hostname: 'gitlab.example.com'
    ports:
      - "8090:80"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    networks: 
      - net
version: "3"
